### ISSUE TITLE
Make rasptimer depend on package at

### ISSUE THREAD

**Issue by jernst** [jernst/rasptimer#4]
Otherwise the "run for 1 hour" functionality does not work.

**Comment by iYoungblood** [comment]
What is the fix for this? It looks like at doesnt exist on my Pi. Do you happen to know where I can find the correct rpm?

**Comment by iYoungblood** [comment]
sudo apt-get install at

heh. :|

**Comment by jernst** [comment]
Not understanding your comment ... this is for UBOS, not debian/raspbian/ubuntu or whatever you are assuming when you are saying `apt-get`.

**Comment by jernst** [comment]
This was fixed in 5f0efbcd7e38f425e6a8595638e23d9e8e5c22c4.

**Comment by iYoungblood** [comment]
Yes, trying to get it to work on raspbian... almost there. Thanks for the comments.
